name: Publish Package to npmjs
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This already includes a build step, but we can also be more explicit if we want.
      - run: echo 1;
